import { expect, test } from '@playwright/test'
import {
  addCriterion, addOption, card, cardBox, closeEditor, dialog, docSection, dragCard, drawRectangle, indicator,
  loadExample, openApp, openDetails, SECTION_ORDER, setCardValue, setTitle, toMode,
} from './helpers'

const names = SECTION_ORDER.map(([, n]) => n)

test('doc-01 toggle keeps state; heading, subtitle, last updated; document column and TOC', async ({ page }) => {
  await openApp(page)
  await setTitle(page, 'Fraud Detection')
  await setCardValue(page, 'problem-space', 'Domain', 'Payments')
  await toMode(page, 'Document')
  const doc = page.getByTestId('document')
  await expect(doc.getByRole('heading', { level: 1 })).toHaveText('Fraud Detection')
  await expect(doc.getByText('ML System Architecture Spec')).toBeVisible()
  await expect(doc.getByText(/^Last updated: /)).toBeVisible()
  const toc = page.getByRole('navigation', { name: 'On this page' })
  await expect(toc).toBeVisible()
  const docBox = (await doc.boundingBox())!
  const tocBox = (await toc.boundingBox())!
  expect(tocBox.x).toBeGreaterThan(docBox.x + docBox.width)
  await toMode(page, 'Canvas')
  await expect(card(page, 'problem-space').getByRole('button', { name: 'Edit Domain' })).toHaveText('Payments')
  await expect(page.getByRole('button', { name: 'Edit Design title' })).toHaveText('Fraud Detection')
})

test('doc-02 numbered headings in canonical order regardless of card layout', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  const psBox = await cardBox(page, 'problem-space')
  await dragCard(page, 'monitoring', 'problem-space')
  expect(await cardBox(page, 'monitoring')).toMatchObject({ x: psBox.x, y: psBox.y })
  await toMode(page, 'Document')
  await expect(page.getByTestId('document').getByRole('heading', { level: 2 })).toHaveText(names.map((n, i) => `${i + 1}. ${n}`))
})

test('doc-03 filled section: plate, rationale, matrix with chosen mark, diagram image; empty parts omitted', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  await toMode(page, 'Document')
  const ts = docSection(page, 'target-solution')
  await expect(ts.getByTestId('key-properties')).toContainText('Gradient Boosted Machine')
  await expect(ts.getByTestId('rationale')).toContainText('Gradient boosting handles tabular')
  const matrix = ts.getByRole('table', { name: 'Trade-off matrix' })
  await expect(matrix.locator('tbody tr')).toHaveCount(3)
  await expect(matrix.locator('tr[data-chosen="true"]')).toHaveCount(1)
  await expect(matrix.locator('tr[data-chosen="true"]').getByRole('textbox', { name: 'Option 1 name' })).toHaveValue('XGBoost')
  await expect(matrix.locator('tr[data-chosen="true"]').getByText('(chosen)')).toHaveCount(1)
  await expect(ts.getByRole('img', { name: /diagram/ })).toBeVisible()
  // Problem Space has no matrix and no diagram in the example.
  const ps = docSection(page, 'problem-space')
  await expect(ps.getByTestId('key-properties')).toBeVisible()
  await expect(ps.getByTestId('doc-matrix')).toHaveCount(0)
  await expect(ps.getByRole('img')).toHaveCount(0)
  // A section with only a key property shows only the plate.
  await toMode(page, 'Canvas')
  await openDetails(page, 'problem-space')
  await dialog(page).getByRole('textbox', { name: 'Rationale' }).fill('')
  await closeEditor(page)
  await toMode(page, 'Document')
  await expect(ps.getByTestId('rationale')).toHaveCount(0)
})

test('doc-04 empty section shows heading and Not filled yet', async ({ page }) => {
  await openApp(page)
  await setCardValue(page, 'baseline', 'Approach', 'Rules')
  await toMode(page, 'Document')
  for (const [sid, name] of SECTION_ORDER) {
    const s = docSection(page, sid)
    await expect(s.getByRole('heading')).toContainText(name)
    if (sid === 'baseline') await expect(s.getByText('Not filled yet')).toHaveCount(0)
    else await expect(s.getByText('Not filled yet')).toBeVisible()
  }
})

test('doc-05 TOC lists all sections, scrolls on click, highlights the section in view', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  await toMode(page, 'Document')
  const toc = page.getByRole('navigation', { name: 'On this page' })
  await expect(toc.getByRole('link')).toHaveText(names)
  await expect(toc.getByRole('link', { name: 'Problem Space' })).toHaveAttribute('aria-current', 'location')
  await toc.getByRole('link', { name: 'Integration' }).click()
  await expect(docSection(page, 'integration')).toBeInViewport()
  await expect(toc.getByRole('link', { name: 'Integration' })).toHaveAttribute('aria-current', 'location')
  await expect(toc.locator('[aria-current]')).toHaveCount(1)
  // Scrolling by hand moves the highlight too.
  await docSection(page, 'baseline').evaluate((e) => e.scrollIntoView())
  await expect(toc.getByRole('link', { name: 'Baseline' })).toHaveAttribute('aria-current', 'location')
})

test('doc-06 inline edit of key property in the document updates the card', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  await toMode(page, 'Document')
  const s = docSection(page, 'integration')
  await s.getByRole('button', { name: 'Edit Inference Pattern' }).click()
  await s.getByRole('textbox', { name: 'Inference Pattern' }).fill('Streaming')
  await s.getByRole('textbox', { name: 'Inference Pattern' }).press('Enter')
  await expect(s.getByRole('button', { name: 'Edit Inference Pattern' })).toHaveText('Streaming')
  await toMode(page, 'Canvas')
  await expect(card(page, 'integration').getByRole('button', { name: 'Edit Inference Pattern' })).toHaveText('Streaming')
})

test('doc-07 inline edit of rationale in the document shows in the Component Editor', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  await toMode(page, 'Document')
  const ed = docSection(page, 'integration').getByRole('textbox', { name: 'Integration rationale' })
  await expect(ed).toHaveAttribute('contenteditable', 'true')
  await ed.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.type(' Needs Kafka')
  await toMode(page, 'Canvas')
  await openDetails(page, 'integration')
  await expect(dialog(page).getByRole('textbox', { name: 'Rationale' })).toContainText('Needs Kafka')
})

test('doc-08 inline edit of matrix in the document updates editor and card indicator', async ({ page }) => {
  await openApp(page)
  await loadExample(page)
  await toMode(page, 'Document')
  const m = docSection(page, 'baseline').getByTestId('doc-matrix')
  await m.getByRole('textbox', { name: 'Cell 2,1' }).fill('Changed')
  await m.getByRole('textbox', { name: 'Option 2 name' }).fill('LogReg')
  await m.getByRole('button', { name: 'Choose option 2' }).click()
  await expect(m.locator('tbody tr').nth(1)).toHaveAttribute('data-chosen', 'true')
  await m.getByRole('textbox', { name: 'Cell 1,1' }).fill('')
  await toMode(page, 'Canvas')
  await expect(indicator(card(page, 'baseline'), 'Trade-offs')).toHaveAttribute('data-state', 'off')
  await openDetails(page, 'baseline')
  const d = dialog(page)
  await expect(d.getByRole('textbox', { name: 'Cell 2,1' })).toHaveValue('Changed')
  await expect(d.getByRole('textbox', { name: 'Option 2 name' })).toHaveValue('LogReg')
  await expect(d.getByRole('button', { name: 'Choose option 2' })).toHaveAttribute('aria-pressed', 'true')
})

test('sync-01 canvas edits show in document and back, for key properties, rationale, trade-offs and diagram', async ({ page }) => {
  await openApp(page)
  // Canvas -> Document
  await setCardValue(page, 'monitoring', 'Data Drift', 'PSI < 0.2')
  await openDetails(page, 'monitoring')
  const d = dialog(page)
  await d.getByRole('textbox', { name: 'Rationale' }).fill('Watch drift daily')
  await addCriterion(d, 'Cost')
  await addOption(d, 'Batch', ['Low'])
  await addOption(d, 'Stream', ['High'])
  await d.getByRole('button', { name: 'Choose option 1' }).click()
  await drawRectangle(page)
  await closeEditor(page)
  await toMode(page, 'Document')
  const s = docSection(page, 'monitoring')
  await expect(s.getByTestId('key-properties')).toContainText('PSI < 0.2')
  await expect(s.getByTestId('rationale')).toContainText('Watch drift daily')
  await expect(s.getByRole('textbox', { name: 'Option 2 name' })).toHaveValue('Stream')
  await expect(s.getByRole('img', { name: 'Monitoring diagram' })).toBeVisible()
  // Document -> Canvas
  await s.getByRole('button', { name: 'Edit Data Drift' }).click()
  await s.getByRole('textbox', { name: 'Data Drift' }).fill('KS test')
  await s.getByRole('textbox', { name: 'Data Drift' }).press('Enter')
  await s.getByRole('textbox', { name: 'Monitoring rationale' }).click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.type(' and weekly')
  await s.getByRole('textbox', { name: 'Cell 2,1' }).fill('Very high')
  await toMode(page, 'Canvas')
  await expect(card(page, 'monitoring').getByRole('button', { name: 'Edit Data Drift' })).toHaveText('KS test')
  await expect(indicator(card(page, 'monitoring'), 'Diagram')).toHaveAttribute('data-state', 'on')
  await expect(card(page, 'monitoring').getByTestId('thumbnail').locator('img')).toBeVisible()
  await openDetails(page, 'monitoring')
  await expect(d.getByRole('textbox', { name: 'Rationale' })).toContainText('Watch drift daily and weekly')
  await expect(d.getByRole('textbox', { name: 'Cell 2,1' })).toHaveValue('Very high')
})
