// Builds supabase/functions/_shared/skill.generated.ts from vendor/ml-system-design-review (docs/backend-spec.md §2).
// Run: pnpm gen:skill. A unit test fails when the committed file is out of date.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const VENDOR = `${ROOT}vendor/ml-system-design-review`
export const OUT = `${ROOT}supabase/functions/_shared/skill.generated.ts`

/** Dimension names from the 'Base MLSD Gradecard' table of references/rubrics.md, plus 'Modern AI'. */
export function dimensions(rubrics: string): string[] {
  const table = rubrics.slice(rubrics.indexOf('## Base MLSD Gradecard'))
  const rows = table.split('\n').filter((l) => l.startsWith('| ') && !l.startsWith('| Dimension') && !l.startsWith('|---'))
  const names: string[] = []
  for (const l of rows) {
    names.push(l.split('|')[1].trim())
    if (names.length === 10) break
  }
  return [...names, 'Modern AI']
}

export function generate(): string {
  const refs = readdirSync(`${VENDOR}/references`).filter((f) => f.endsWith('.md')).sort()
  const parts = [['SKILL.md', readFileSync(`${VENDOR}/SKILL.md`, 'utf8')], ...refs.map((f) => [`references/${f}`, readFileSync(`${VENDOR}/references/${f}`, 'utf8')])]
  const skill = parts.map(([name, text]) => `<file name="${name}">\n${text.trim()}\n</file>`).join('\n\n')
  const dims = dimensions(readFileSync(`${VENDOR}/references/rubrics.md`, 'utf8'))
  return [
    '// Generated by `pnpm gen:skill` from vendor/ml-system-design-review. Do not edit by hand.',
    '',
    '/** SKILL.md and its references, as the model reads them. */',
    `export const SKILL = ${JSON.stringify(skill)}`,
    '',
    '/** Rubric dimensions: the 10 of the base gradecard and Modern AI (docs/backend-spec.md §6.5). */',
    `export const DIMENSIONS = ${JSON.stringify(dims, null, 2)} as const`,
    '',
  ].join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, generate())
  console.log(`wrote ${OUT}`)
}
